[project]
name = "checkmk-wizard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "kone", email = "guyver30@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "asyncssh>=2.24.0",
    "httpx>=0.28.1",
    "questionary>=2.1.1",
    "rich>=15.0.0",
]

[project.scripts]
checkmk-wizard = "checkmk_wizard.wizard:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "respx>=0.23.1",
]
