/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { BannerPosition, BannerType } from "./components/molecules/kfds-banner/kfds-banner.enum";
import { ButtonSize, ButtonStyle, ButtonType } from "./components/atoms/kfds-button/kfds-button.enum";
import { CheckboxOption, CheckboxOrientation, CheckboxSize } from "./components/atoms/kfds-checkbox/kfds-checkbox.enum";
import { InputShape, InputSize } from "./components/atoms/kfds-input/kfds-input.enum";
import { RadioOption, RadioOrientation, RadioSize } from "./components/atoms/kfds-radio/kfds-radio.enum";
import { selectOption, SelectShape, SelectSize } from "./components/atoms/kfds-select/kfds-select.enum";
import { TooltipPosition, TooltipStyle } from "./components/atoms/kfds-tooltip/kfds-tooltip.enum";
export { BannerPosition, BannerType } from "./components/molecules/kfds-banner/kfds-banner.enum";
export { ButtonSize, ButtonStyle, ButtonType } from "./components/atoms/kfds-button/kfds-button.enum";
export { CheckboxOption, CheckboxOrientation, CheckboxSize } from "./components/atoms/kfds-checkbox/kfds-checkbox.enum";
export { InputShape, InputSize } from "./components/atoms/kfds-input/kfds-input.enum";
export { RadioOption, RadioOrientation, RadioSize } from "./components/atoms/kfds-radio/kfds-radio.enum";
export { selectOption, SelectShape, SelectSize } from "./components/atoms/kfds-select/kfds-select.enum";
export { TooltipPosition, TooltipStyle } from "./components/atoms/kfds-tooltip/kfds-tooltip.enum";
export namespace Components {
    interface KfdsBanner {
        "actions": any;
        "customClass": string;
        "elementId": string;
        "message": string;
        "position": BannerPosition;
        "type": BannerType;
    }
    interface KfdsBreadcrumb {
        "customClass": string;
        "elementId": string;
        "isTruncated": boolean;
        "links": any;
        "size": string;
        "type": string;
    }
    interface KfdsButton {
        "buttonStyle": ButtonStyle;
        "customClass": string;
        "disabled": boolean;
        "elementId": string;
        "size": ButtonSize;
        "type": ButtonType;
    }
    interface KfdsCheckbox {
        "customClass": string;
        "disabled": boolean;
        "elementId": string;
        "label": string;
        "name": string;
        "options": CheckboxOption[] | any;
        "orientation": CheckboxOrientation;
        "required": boolean;
        "selectedOptions": any;
        "size": CheckboxSize;
    }
    interface KfdsHyperlink {
        "customClass": string;
        "elementId": string;
        "href": string;
        "target": any;
    }
    interface KfdsInput {
        "customClass": string;
        "disabled": boolean;
        "elementId": string;
        "floating": boolean;
        "label": string;
        "maxLength": number;
        "name": string;
        "placeholder": string;
        "required": boolean;
        "shape": InputShape;
        "size": InputSize;
        "supportingText": string;
        "type": string;
        "value": string;
    }
    interface KfdsLoader {
        "appName": string;
        "customClass": string;
        "elementId": string;
        "now": number;
        "progressBar": 'show' | 'hidden';
        "progressNum": 'show' | 'hidden';
        "restartButton": 'show' | 'hidden';
        "videoBackground": 'show' | 'hidden';
    }
    interface KfdsMessage {
        "actions": any;
        "customClass": string;
        "elementId": string;
        "messageTitle": string;
        "position": string;
        "type": string;
    }
    interface KfdsModal {
        "actions": any;
        "elementId": string;
        "modalTitle": string;
        "showIllustration": boolean;
        "visible": boolean;
    }
    interface KfdsRadio {
        "customClass": string;
        "disabled": boolean;
        "elementId": string;
        "label": string;
        "name": string;
        "options": RadioOption[] | any;
        "orientation": RadioOrientation;
        "required": boolean;
        "selectedOption": any;
        "size": RadioSize;
    }
    interface KfdsSelect {
        "customClass": string;
        "disabled": boolean;
        "elementId": string;
        "label": string;
        "name": string;
        "options": selectOption[] | any;
        "placeholder": string;
        "required": boolean;
        "selectedOption": any;
        "shape": SelectShape;
        "size": SelectSize;
        "supportingText": string;
    }
    interface KfdsSlider {
        "customClass": string;
        "disabled": boolean;
        "elementId": string;
        "label": string;
        "max": number;
        "min": number;
        "required": boolean;
        "selectedValue": number;
        "showLabel": boolean;
        "showNumberInput": boolean;
        "showSupportingText": boolean;
        "sliderClass": string;
        "supportingText": string;
        "unit": string;
    }
    interface KfdsSnackbar {
        "actions": any;
        "autoHide": boolean;
        "customClass": string;
        "duration": number;
        "elementId": string;
        "horizontalPosition": string;
        "message": string;
        "showClose": boolean;
        "type": string;
        "verticalPosition": string;
        "visible": boolean;
    }
    interface KfdsTooltip {
        "customClass": string;
        "elementId": string;
        "position": TooltipPosition;
        "text": string;
        "tooltipStyle": TooltipStyle;
    }
}
export interface KfdsBannerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsBannerElement;
}
export interface KfdsBreadcrumbCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsBreadcrumbElement;
}
export interface KfdsButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsButtonElement;
}
export interface KfdsCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsCheckboxElement;
}
export interface KfdsHyperlinkCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsHyperlinkElement;
}
export interface KfdsInputCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsInputElement;
}
export interface KfdsMessageCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsMessageElement;
}
export interface KfdsModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsModalElement;
}
export interface KfdsRadioCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsRadioElement;
}
export interface KfdsSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsSelectElement;
}
export interface KfdsSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsSliderElement;
}
export interface KfdsSnackbarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLKfdsSnackbarElement;
}
declare global {
    interface HTMLKfdsBannerElement extends Components.KfdsBanner, HTMLStencilElement {
    }
    var HTMLKfdsBannerElement: {
        prototype: HTMLKfdsBannerElement;
        new (): HTMLKfdsBannerElement;
    };
    interface HTMLKfdsBreadcrumbElement extends Components.KfdsBreadcrumb, HTMLStencilElement {
    }
    var HTMLKfdsBreadcrumbElement: {
        prototype: HTMLKfdsBreadcrumbElement;
        new (): HTMLKfdsBreadcrumbElement;
    };
    interface HTMLKfdsButtonElement extends Components.KfdsButton, HTMLStencilElement {
    }
    var HTMLKfdsButtonElement: {
        prototype: HTMLKfdsButtonElement;
        new (): HTMLKfdsButtonElement;
    };
    interface HTMLKfdsCheckboxElement extends Components.KfdsCheckbox, HTMLStencilElement {
    }
    var HTMLKfdsCheckboxElement: {
        prototype: HTMLKfdsCheckboxElement;
        new (): HTMLKfdsCheckboxElement;
    };
    interface HTMLKfdsHyperlinkElement extends Components.KfdsHyperlink, HTMLStencilElement {
    }
    var HTMLKfdsHyperlinkElement: {
        prototype: HTMLKfdsHyperlinkElement;
        new (): HTMLKfdsHyperlinkElement;
    };
    interface HTMLKfdsInputElement extends Components.KfdsInput, HTMLStencilElement {
    }
    var HTMLKfdsInputElement: {
        prototype: HTMLKfdsInputElement;
        new (): HTMLKfdsInputElement;
    };
    interface HTMLKfdsLoaderElement extends Components.KfdsLoader, HTMLStencilElement {
    }
    var HTMLKfdsLoaderElement: {
        prototype: HTMLKfdsLoaderElement;
        new (): HTMLKfdsLoaderElement;
    };
    interface HTMLKfdsMessageElement extends Components.KfdsMessage, HTMLStencilElement {
    }
    var HTMLKfdsMessageElement: {
        prototype: HTMLKfdsMessageElement;
        new (): HTMLKfdsMessageElement;
    };
    interface HTMLKfdsModalElement extends Components.KfdsModal, HTMLStencilElement {
    }
    var HTMLKfdsModalElement: {
        prototype: HTMLKfdsModalElement;
        new (): HTMLKfdsModalElement;
    };
    interface HTMLKfdsRadioElement extends Components.KfdsRadio, HTMLStencilElement {
    }
    var HTMLKfdsRadioElement: {
        prototype: HTMLKfdsRadioElement;
        new (): HTMLKfdsRadioElement;
    };
    interface HTMLKfdsSelectElement extends Components.KfdsSelect, HTMLStencilElement {
    }
    var HTMLKfdsSelectElement: {
        prototype: HTMLKfdsSelectElement;
        new (): HTMLKfdsSelectElement;
    };
    interface HTMLKfdsSliderElement extends Components.KfdsSlider, HTMLStencilElement {
    }
    var HTMLKfdsSliderElement: {
        prototype: HTMLKfdsSliderElement;
        new (): HTMLKfdsSliderElement;
    };
    interface HTMLKfdsSnackbarElement extends Components.KfdsSnackbar, HTMLStencilElement {
    }
    var HTMLKfdsSnackbarElement: {
        prototype: HTMLKfdsSnackbarElement;
        new (): HTMLKfdsSnackbarElement;
    };
    interface HTMLKfdsTooltipElement extends Components.KfdsTooltip, HTMLStencilElement {
    }
    var HTMLKfdsTooltipElement: {
        prototype: HTMLKfdsTooltipElement;
        new (): HTMLKfdsTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "kfds-banner": HTMLKfdsBannerElement;
        "kfds-breadcrumb": HTMLKfdsBreadcrumbElement;
        "kfds-button": HTMLKfdsButtonElement;
        "kfds-checkbox": HTMLKfdsCheckboxElement;
        "kfds-hyperlink": HTMLKfdsHyperlinkElement;
        "kfds-input": HTMLKfdsInputElement;
        "kfds-loader": HTMLKfdsLoaderElement;
        "kfds-message": HTMLKfdsMessageElement;
        "kfds-modal": HTMLKfdsModalElement;
        "kfds-radio": HTMLKfdsRadioElement;
        "kfds-select": HTMLKfdsSelectElement;
        "kfds-slider": HTMLKfdsSliderElement;
        "kfds-snackbar": HTMLKfdsSnackbarElement;
        "kfds-tooltip": HTMLKfdsTooltipElement;
    }
}
declare namespace LocalJSX {
    interface KfdsBanner {
        "actions"?: any;
        "customClass"?: string;
        "elementId"?: string;
        "message"?: string;
        "onActionLinkClicked"?: (event: KfdsBannerCustomEvent<string>) => void;
        "position"?: BannerPosition;
        "type"?: BannerType;
    }
    interface KfdsBreadcrumb {
        "customClass"?: string;
        "elementId"?: string;
        "isTruncated"?: boolean;
        "links"?: any;
        "onItemClicked"?: (event: KfdsBreadcrumbCustomEvent<string>) => void;
        "size"?: string;
        "type"?: string;
    }
    interface KfdsButton {
        "buttonStyle"?: ButtonStyle;
        "customClass"?: string;
        "disabled"?: boolean;
        "elementId"?: string;
        "onButtonClicked"?: (event: KfdsButtonCustomEvent<any>) => void;
        "size"?: ButtonSize;
        "type"?: ButtonType;
    }
    interface KfdsCheckbox {
        "customClass"?: string;
        "disabled"?: boolean;
        "elementId"?: string;
        "label"?: string;
        "name"?: string;
        "onCheckboxClicked"?: (event: KfdsCheckboxCustomEvent<string[]>) => void;
        "options"?: CheckboxOption[] | any;
        "orientation"?: CheckboxOrientation;
        "required"?: boolean;
        "selectedOptions"?: any;
        "size"?: CheckboxSize;
    }
    interface KfdsHyperlink {
        "customClass"?: string;
        "elementId"?: string;
        "href"?: string;
        "onLinkClicked"?: (event: KfdsHyperlinkCustomEvent<any>) => void;
        "target"?: any;
    }
    interface KfdsInput {
        "customClass"?: string;
        "disabled"?: boolean;
        "elementId"?: string;
        "floating"?: boolean;
        "label"?: string;
        "maxLength"?: number;
        "name"?: string;
        "onInputBlur"?: (event: KfdsInputCustomEvent<string>) => void;
        "onInputChange"?: (event: KfdsInputCustomEvent<string>) => void;
        "placeholder"?: string;
        "required"?: boolean;
        "shape"?: InputShape;
        "size"?: InputSize;
        "supportingText"?: string;
        "type"?: string;
        "value"?: string;
    }
    interface KfdsLoader {
        "appName"?: string;
        "customClass"?: string;
        "elementId"?: string;
        "now"?: number;
        "progressBar"?: 'show' | 'hidden';
        "progressNum"?: 'show' | 'hidden';
        "restartButton"?: 'show' | 'hidden';
        "videoBackground"?: 'show' | 'hidden';
    }
    interface KfdsMessage {
        "actions"?: any;
        "customClass"?: string;
        "elementId"?: string;
        "messageTitle"?: string;
        "onActionButtonClicked"?: (event: KfdsMessageCustomEvent<string>) => void;
        "position"?: string;
        "type"?: string;
    }
    interface KfdsModal {
        "actions"?: any;
        "elementId"?: string;
        "modalTitle"?: string;
        "onActionButtonClicked"?: (event: KfdsModalCustomEvent<string>) => void;
        "showIllustration"?: boolean;
        "visible"?: boolean;
    }
    interface KfdsRadio {
        "customClass"?: string;
        "disabled"?: boolean;
        "elementId"?: string;
        "label"?: string;
        "name"?: string;
        "onRadioClicked"?: (event: KfdsRadioCustomEvent<string>) => void;
        "options"?: RadioOption[] | any;
        "orientation"?: RadioOrientation;
        "required"?: boolean;
        "selectedOption"?: any;
        "size"?: RadioSize;
    }
    interface KfdsSelect {
        "customClass"?: string;
        "disabled"?: boolean;
        "elementId"?: string;
        "label"?: string;
        "name"?: string;
        "onSelectBlur"?: (event: KfdsSelectCustomEvent<string>) => void;
        "onSelectChange"?: (event: KfdsSelectCustomEvent<string>) => void;
        "options"?: selectOption[] | any;
        "placeholder"?: string;
        "required"?: boolean;
        "selectedOption"?: any;
        "shape"?: SelectShape;
        "size"?: SelectSize;
        "supportingText"?: string;
    }
    interface KfdsSlider {
        "customClass"?: string;
        "disabled"?: boolean;
        "elementId"?: string;
        "label"?: string;
        "max"?: number;
        "min"?: number;
        "onInputBlur"?: (event: KfdsSliderCustomEvent<string>) => void;
        "onInputChange"?: (event: KfdsSliderCustomEvent<string>) => void;
        "required"?: boolean;
        "selectedValue"?: number;
        "showLabel"?: boolean;
        "showNumberInput"?: boolean;
        "showSupportingText"?: boolean;
        "sliderClass"?: string;
        "supportingText"?: string;
        "unit"?: string;
    }
    interface KfdsSnackbar {
        "actions"?: any;
        "autoHide"?: boolean;
        "customClass"?: string;
        "duration"?: number;
        "elementId"?: string;
        "horizontalPosition"?: string;
        "message"?: string;
        "onActionLinkClicked"?: (event: KfdsSnackbarCustomEvent<string>) => void;
        "showClose"?: boolean;
        "type"?: string;
        "verticalPosition"?: string;
        "visible"?: boolean;
    }
    interface KfdsTooltip {
        "customClass"?: string;
        "elementId"?: string;
        "position"?: TooltipPosition;
        "text"?: string;
        "tooltipStyle"?: TooltipStyle;
    }
    interface IntrinsicElements {
        "kfds-banner": KfdsBanner;
        "kfds-breadcrumb": KfdsBreadcrumb;
        "kfds-button": KfdsButton;
        "kfds-checkbox": KfdsCheckbox;
        "kfds-hyperlink": KfdsHyperlink;
        "kfds-input": KfdsInput;
        "kfds-loader": KfdsLoader;
        "kfds-message": KfdsMessage;
        "kfds-modal": KfdsModal;
        "kfds-radio": KfdsRadio;
        "kfds-select": KfdsSelect;
        "kfds-slider": KfdsSlider;
        "kfds-snackbar": KfdsSnackbar;
        "kfds-tooltip": KfdsTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kfds-banner": LocalJSX.KfdsBanner & JSXBase.HTMLAttributes<HTMLKfdsBannerElement>;
            "kfds-breadcrumb": LocalJSX.KfdsBreadcrumb & JSXBase.HTMLAttributes<HTMLKfdsBreadcrumbElement>;
            "kfds-button": LocalJSX.KfdsButton & JSXBase.HTMLAttributes<HTMLKfdsButtonElement>;
            "kfds-checkbox": LocalJSX.KfdsCheckbox & JSXBase.HTMLAttributes<HTMLKfdsCheckboxElement>;
            "kfds-hyperlink": LocalJSX.KfdsHyperlink & JSXBase.HTMLAttributes<HTMLKfdsHyperlinkElement>;
            "kfds-input": LocalJSX.KfdsInput & JSXBase.HTMLAttributes<HTMLKfdsInputElement>;
            "kfds-loader": LocalJSX.KfdsLoader & JSXBase.HTMLAttributes<HTMLKfdsLoaderElement>;
            "kfds-message": LocalJSX.KfdsMessage & JSXBase.HTMLAttributes<HTMLKfdsMessageElement>;
            "kfds-modal": LocalJSX.KfdsModal & JSXBase.HTMLAttributes<HTMLKfdsModalElement>;
            "kfds-radio": LocalJSX.KfdsRadio & JSXBase.HTMLAttributes<HTMLKfdsRadioElement>;
            "kfds-select": LocalJSX.KfdsSelect & JSXBase.HTMLAttributes<HTMLKfdsSelectElement>;
            "kfds-slider": LocalJSX.KfdsSlider & JSXBase.HTMLAttributes<HTMLKfdsSliderElement>;
            "kfds-snackbar": LocalJSX.KfdsSnackbar & JSXBase.HTMLAttributes<HTMLKfdsSnackbarElement>;
            "kfds-tooltip": LocalJSX.KfdsTooltip & JSXBase.HTMLAttributes<HTMLKfdsTooltipElement>;
        }
    }
}
