// Source of truth: design-system/tailwind.config.js. `kone-design-system`'s package.json
// `exports` map only publishes "." and "./style.css" (no config export), so this file
// duplicates that theme.extend block by hand. Every entry here must stay in step with
// design-system/tailwind.config.js by hand whenever that file changes.
/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["selector", '[data-theme="dark"]'],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        fg: {
          primary: "var(--color-fg-primary)",
          secondary: "var(--color-fg-secondary)",
          tertiary: "var(--color-fg-tertiary)",
          placeholder: "var(--color-fg-placeholder)",
          disabled: "var(--color-fg-disabled)",
          brand: "var(--color-fg-brand)",
          "brand-inverse": "var(--color-fg-brand-inverse)",
          danger: "var(--color-fg-danger)",
          warning: "var(--color-fg-warning)",
          success: "var(--color-fg-success)",
          oncolor: "var(--color-fg-oncolor-primary)",
          onwhite: "var(--color-fg-onwhite-primary)",
          link: "var(--color-fg-link-default)",
          "link-visited": "var(--color-fg-link-visited)",
        },
        bg: {
          canvas: "var(--color-bg-canvas-default)",
          surface: "var(--color-bg-surface-default)",
          "surface-hover": "var(--color-bg-surface-hover)",
          "surface-active": "var(--color-bg-surface-active)",
          "surface-disabled": "var(--color-bg-surface-disabled)",
          "subtle": "var(--color-bg-surface-subtle-default)",
          "subtle-hover": "var(--color-bg-surface-subtle-hover)",
          "subtle-active": "var(--color-bg-surface-subtle-active)",
          "subtle-disabled": "var(--color-bg-surface-subtle-disabled)",
          "control-primary": "var(--color-bg-control-primary-default)",
          "control-primary-hover": "var(--color-bg-control-primary-hover)",
          "control-primary-active": "var(--color-bg-control-primary-active)",
          "control-primary-disabled": "var(--color-bg-control-primary-disabled)",
        },
        scrim: "var(--color-scrim)",
        brand: {
          DEFAULT: "var(--color-brand-default)",
          hover: "var(--color-brand-hover)",
          active: "var(--color-brand-active)",
          disabled: "var(--color-brand-disabled)",
          light: "var(--color-brand-light)",
          "light-hover": "var(--color-brand-light-hover)",
          "light-active": "var(--color-brand-light-active)",
          "light-disabled": "var(--color-brand-light-disabled)",
          focus: "var(--color-brand-focus)",
        },
        success: {
          DEFAULT: "var(--color-success-default)",
          hover: "var(--color-success-hover)",
          active: "var(--color-success-active)",
          light: "var(--color-success-light)",
          "light-hover": "var(--color-success-light-hover)",
          "light-active": "var(--color-success-light-active)",
        },
        warning: {
          DEFAULT: "var(--color-warning-default)",
          hover: "var(--color-warning-hover)",
          active: "var(--color-warning-active)",
          light: "var(--color-warning-light)",
          "light-hover": "var(--color-warning-light-hover)",
          "light-active": "var(--color-warning-light-active)",
        },
        alert: {
          DEFAULT: "var(--color-alert-default)",
          hover: "var(--color-alert-hover)",
          active: "var(--color-alert-active)",
          light: "var(--color-alert-light)",
          "light-hover": "var(--color-alert-light-hover)",
          "light-active": "var(--color-alert-light-active)",
        },
        secondary: {
          linen: "var(--linen)",
          sunflower: "var(--sunflower)",
          powderblue: "var(--powderblue)",
          blush: "var(--blush)",
          mint: "var(--mint)",
        },
        neutral: {
          0: "var(--neutral-0)",
          50: "var(--neutral-50)",
          90: "var(--neutral-90)",
          100: "var(--neutral-100)",
          110: "var(--neutral-110)",
          125: "var(--neutral-125)",
          150: "var(--neutral-150)",
          200: "var(--neutral-200)",
          300: "var(--neutral-300)",
          400: "var(--neutral-400)",
          500: "var(--neutral-500)",
          600: "var(--neutral-600)",
          700: "var(--neutral-700)",
          750: "var(--neutral-750)",
          800: "var(--neutral-800)",
          850: "var(--neutral-850)",
          900: "var(--neutral-900)",
          950: "var(--neutral-950)",
        },
        purple: {
          500: "var(--purple-500)",
          600: "var(--purple-600)",
        },
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        pill: "var(--radius-pill)",
      },
      boxShadow: {
        card: "var(--shadow-card)",
        menu: "var(--shadow-menu)",
        tooltip: "var(--shadow-tooltip)",
        focus: "var(--shadow-focus)",
      },
      fontFamily: {
        sans: ["var(--font-family-base)", "sans-serif"],
      },
      fontSize: {
        xs: "var(--font-size-xs)",
        sm: "var(--font-size-sm)",
        base: "var(--font-size-base)",
        lg: "var(--font-size-lg)",
        xl: "var(--font-size-xl)",
        "2xl": "var(--font-size-2xl)",
      },
    },
  },
  plugins: [],
};
